"""Build small display copies; keep the original photos untouched."""

from pathlib import Path
from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
PREVIEW = ASSETS / "preview"
GALLERY = ASSETS / "gallery"

# SVG renders these illustrations at much smaller sizes than their source PNGs.
MAP_ART = {
    "xiamen-overview-watercolor-v2.png": 1536,
    "xiamen-landmarks-v2.png": 656,
    "xiamen-hotel-watercolor-v1.png": 240,
    "xiamen-station-watercolor-v1.png": 400,
    "xiamen-zhongshan-watercolor-v1.png": 240,
    "xiamen-yujian-watercolor-v1.png": 240,
}


def save_preview(source: Path, destination: Path, max_edge: int) -> None:
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original)
        image.thumbnail((max_edge, max_edge), Image.Resampling.LANCZOS)
        if image.mode not in ("RGB", "RGBA"):
            image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
        destination.parent.mkdir(parents=True, exist_ok=True)
        image.save(destination, "WEBP", quality=86, method=6)


def main() -> None:
    paths = {}
    for name, max_edge in MAP_ART.items():
        save_preview(ASSETS / name, PREVIEW / f"{Path(name).stem}.webp", max_edge)
    for source in sorted(GALLERY.iterdir()):
        if source.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp"}:
            continue
        if source.stat().st_size <= 350_000:
            continue
        destination = PREVIEW / f"{source.name}.webp"
        save_preview(source, destination, 1600)
        if destination.stat().st_size >= source.stat().st_size:
            destination.unlink()
            continue
        paths[f"assets/gallery/{source.name}"] = f"assets/preview/{destination.name}"
    for source in sorted(ASSETS.iterdir()):
        if source.suffix.lower() not in {".jpg", ".jpeg"}:
            continue
        if source.stat().st_size <= 350_000:
            continue
        destination = PREVIEW / f"{source.name}.webp"
        save_preview(source, destination, 1600)
        if destination.stat().st_size >= source.stat().st_size:
            destination.unlink()
            continue
        paths[f"assets/{source.name}"] = f"assets/preview/{destination.name}"
    lines = ["// Generated by scripts/optimize-mobile-images.py; original photos stay in assets/.",
             "window.XiamenImagePreviews = {"]
    lines.extend(f"  '{source}': '{preview}'," for source, preview in paths.items())
    lines.append("};")
    (ROOT / "image-previews.js").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(MAP_ART)} map previews and {len(paths)} photo previews")


if __name__ == "__main__":
    main()
